version: '3.8'

services:
  springboot-app:
    image: springboot:latest
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_db_name
    ports:
      - "3306:3306"
