version: '3.8'

services:
  app:
    build: .
    container_name: adventure-zeyno-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/adventurexp?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: cocomelon
      SPRING_DATASOURCE_PASSWORD: cocomelon
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: adventure-zeyno-db
    environment:

      MYSQL_ROOT_PASSWORD: 12Qwe++!
      MYSQL_DATABASE: adventurexp
      MYSQL_USER: cocomelon
      MYSQL_PASSWORD: cocomelon

    ports:
      - "3307:3306"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql  # Mount the SQL file
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
